"""empty message

Revision ID: 41abbaa0906f
Revises: fae567b22d88
Create Date: 2019-05-15 17:48:43.464556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abbaa0906f'
down_revision = 'fae567b22d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('last_month', sa.Float(), nullable=True),
    sa.Column('avg_month', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=128), nullable=True),
    sa.Column('apply', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'unique_transactions', 'transaction', type_='unique')
    op.create_unique_constraint('unique_transactions', 'transaction', ['date', 'amount', 'type', 'description', 'category', 'subcategory'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_transactions', 'transaction', type_='unique')
    op.create_unique_constraint(u'unique_transactions', 'transaction', ['account_id', 'date', 'amount', 'type', 'description', 'category', 'subcategory'])
    op.drop_table('subcategory_settings')
    # ### end Alembic commands ###
