"""empty message

Revision ID: 9b8e5fa55042
Revises: 5ed46c5425f7
Create Date: 2020-03-24 22:47:55.357774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8e5fa55042'
down_revision = '5ed46c5425f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtransaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('beneficiary', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbtransaction_date'), 'dbtransaction', ['date'], unique=False)
    #op.drop_constraint(u'unique_transactions', 'transaction', type_='unique')
    #op.create_unique_constraint('unique_transactions', 'transaction', ['date', 'amount', 'type', 'description', 'category', 'subcategory'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('unique_transactions', 'transaction', type_='unique')
    #op.create_unique_constraint(u'unique_transactions', 'transaction', ['account_id', 'date', 'amount', 'type', 'description', 'category', 'subcategory'])
    op.drop_index(op.f('ix_dbtransaction_date'), table_name='dbtransaction')
    op.drop_table('dbtransaction')
    # ### end Alembic commands ###
